version: '3.7'

services:
  app:
    build: .
    container_name: node_app
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env

  grpc-test:
    image: gusaul/grpcox:latest
    env_file: .env
    ports:
      - ${TEST_GRPC_PORT}:${TEST_GRPC_PORT}
